name: xpinmame_lisy
on:
  push:

jobs:
  build:
    name: ${{ matrix.cpu_info }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero, zero2_64]
        include:
          - target: zero
            cpu: arm1176
            cpu_info: raspberrypi_zero_w
            base_image: raspios_lite:latest
          - target: zero2_64
            cpu: cortex-a53
            cpu_info: raspberrypi_zero2_w_arm64
            base_image: raspios_lite_arm64:latest
    steps:
      - name: Checkout pinmame
        uses: actions/checkout@v3

      - name: Checkout WiringPi
        uses: actions/checkout@v3
        with:
            repository: WiringPi/WiringPi
            ref: master
            path: WiringPi

      - name: Make in chroot environment
        uses: pguyot/arm-runner-action@v2
        id: arm_runner_make
        with:
          base_image: ${{ matrix.base_image }}
          optimize_image: yes
          image_additional_mb: 1024
          cpu: ${{ matrix.cpu }}
          cpu_info: cpuinfo/${{ matrix.cpu_info }}
          copy_repository_path: /opt/pinmame
          copy_artifact_path: xpinmame.vid_lisy
          commands: |
            apt-get update -y --allow-releaseinfo-change
            apt-get install --no-install-recommends -y libasound2-dev libsdl2.dev libsdl2-mixer-dev libi2c-dev
            cd /opt/pinmame/WiringPi
            ./build
            cd /opt/pinmame
            make -f makefile.lisy

      - name: Upload xmpinmame binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: LISY xpinmame ${{ matrix.cpu_info }}
          path: xpinmame.vid_lisy
